export const BOOKS_STATE_REQUEST = 'BOOKS_STATE_REQUEST'
export const BOOKS_STATE_SUCCESS = 'BOOKS_STATE_SUCCESS'
export const BOOKS_STATE_FAILURE = 'BOOKS_STATE_FAILURE'
export const OUR_BOOKS_STATE_REQUEST = 'OUR_BOOKS_STATE_REQUEST'
export const OUR_BOOKS_STATE_SUCCESS = 'OUR_BOOKS_STATE_SUCCESS'
export const OUR_BOOKS_STATE_FAILURE = 'OUR_BOOKS_STATE_FAILURE'


